manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: finestedm
      url-base: https://github.com/finestedm
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: Temper_zmk
      remote: finestedm
      revision: main
  self:
    path: config
